language: bash
sudo: required
script:
  - sudo ./.travis.sh
env:
  - PACKAGES="app-admin/linode-cli:{0,4} app-admin/pass-otp app-misc/{blinkstick,cronic,gotty-bin,tty-clock,wemux} app-shells/elvish app-vim/neovim-remote"
  - PACKAGES="dev-embedded/{arduino-bin,energia-bin,teensyduino-bin} dev-python/{pandocfilters,slixmpp,twilio,vex} dev-util/ffdec"
  - PACKAGES="games-action/armagetronad{,-dedicated} games-arcade/nsnake games-misc/{git-fire,lolcat,nyancat,pipes}"
  - PACKAGES="media-gfx/{maim,sk1} media-libs/openvr media-plugins/{calf,gxplugins-lv2,midifilter-lv2} media-sound/{gxtuner,ympd} media-tv/{airtame-bin,plex-media-server,plexpy} media-video/v4l2loopback"
  - PACKAGES="net-fs/pingfs net-im/{discord-bin,slack-bin} net-mail/syncmaildir net-p2p/zget net-wireless/{create_ap,unifi}"
  - PACKAGES="sci-electronics/{eagle,freeroute,fritzing-bin} sci-physics/chipmunk"
  - PACKAGES="sys-apps/petty sys-boot/{mkusb,mkwin} sys-fs/{exfat-nofuse,pifs,udiskie} sys-kernel/pf-sources www-servers/pagekite"
  - PACKAGES="x11-misc/{awf,barline,clipster,lemonbar,rofi-pass,slop} x11-themes/arc-openbox-theme"
