language: bash
sudo: required
script:
  - sudo ./.travis.sh
env:
  - PACKAGES="app-admin/pass-otp app-misc/{blinkstick,cronic,gotty-bin,tty-clock,wemux} app-shells/elvish"
  - PACKAGES="app-admin/linode-cli:{0,4} app-vim/neovim-remote"
  - PACKAGES="dev-embedded/{arduino-bin,energia-bin,teensyduino-bin} dev-python/{pandocfilters,slixmpp}"
  - PACKAGES="dev-python/{twilio,vex}"
  - PACKAGES="dev-util/ffdec"
  - PACKAGES="games-action/armagetronad"
  - PACKAGES="games-action/armagetronad-dedicated"
  - PACKAGES="games-arcade/nsnake games-misc/{git-fire,lolcat,nyancat,pipes}"
  - PACKAGES="media-gfx/{maim,sk1} media-libs/openvr media-plugins/{calf,gxplugins-lv2,midifilter-lv2} media-sound/{gxtuner,ympd} media-tv/{airtame-bin,plex-media-server,plexpy} media-video/v4l2loopback"
  - PACKAGES="net-fs/pingfs net-mail/syncmaildir"
  - PACKAGES="net-im/{discord-bin,slack-bin}"
  - PACKAGES="net-p2p/zget net-wireless/create_ap"
  - PACKAGES="net-wireless/unifi"
  - PACKAGES="sci-electronics/eagle sci-physics/chipmunk"
  - PACKAGES="sci-electronics/freeroute"
  - PACKAGES="sci-electronics/fritzing-bin"
  - PACKAGES="sys-apps/petty sys-kernel/pf-sources www-servers/pagekite"
  - PACKAGES="sys-boot/{mkusb,mkwin} sys-fs/{pifs,udiskie}"
  - PACKAGES="x11-misc/{barline,clipster,lemonbar} x11-themes/arc-openbox-theme"
  - PACKAGES="x11-misc/{rofi-pass,slop}"
  - PACKAGES="x11-misc/awf"
